parameters:
    gwinn.cypher.class: Gwinn\ScuthBundle\Component\Security\Cypher
    gwinn.property.class: Gwinn\ScuthBundle\Component\ProtectedAccessor

services:
    gwinn.cypher:
        class: %gwinn.cypher.class%
        arguments: [@service_container]

    gwinn.accessor:
        class: %gwinn.property.class%
        arguments: [@service_container]